name: PR Builder Reports
on:
  workflow_run:
    workflows: [ "PR Builder" ]
    types:
      - completed
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      # Matrix should be coordinated with ci-prb.yml.
      matrix:
        java: [ 8, 11 ]
        os: [ ubuntu-latest ]
    steps:
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: completed
          commit: ${{ github.event.workflow_run.head_commit.id }}
          # File location set in ci-prb.yml and must be coordinated.
          name: test-results-${{ matrix.os }}-${{ matrix.java }}
      - name: Publish Test Report
        uses: scacap/action-surefire-report@4a5ec3cb2aaa41baed5e4b431ea9a43eb6ad1c9c
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
          commit: ${{ github.event.workflow_run.head_commit.id }}
          check_name: Test Report JDK ${{ matrix.java }} ${{ matrix.os }}
